package com.arvue.apps.projectx;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Component;
import org.vaadin.teemu.clara.binder.annotation.UiHandler;
import com.vaadin.addon.touchkit.ui.NavigationView;

public class MainController {

    @AutoGenerated
    private NavigationView root;

    @AutoGenerated
    public void setRootComponent(Component root) {
        this.root = (NavigationView) root;
    }

    @UiHandler("button_1")
    public void handleButtonClick(ClickEvent event) {
        event.getButton().setCaption("Clicked!");
    }
}
